api_version = "2025-04"

[[extensions]]

uid = "2ad4293a-c48b-4db9-3196-d5f07c030a2806d8ad17"

type = "ui_extension"
name = "HOCS Payment Redirect"
handle = "hocs-payment-redirect"

  [[extensions.targeting]]
  target = "purchase.thank-you.block.render"
  module = "./src/ThankYouPayment.jsx"

  [[extensions.targeting]]
  target = "customer-account.order-status.block.render"
  module = "./src/ThankYouPayment.jsx"

[extensions.capabilities]
# network_access lets the extension fetch from external domains
network_access = true
